### ISSUE TITLE
 BUG: DashboardTest.testLogin:76 » Timeout Timed out after 2 seconds waiting for vis...

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/InciDashboard_e3b#23]
Fallo en la ejecución de las pruebas unitarias con Selenium: `DashboardTest.testLogin:76`:
~~~
2018-05-22 13:57:50.563  INFO 4952 --- [           main] e.u.a.e.incidashboard_e3b.DashboardTest  : Started DashboardTest in 36.72 seconds (JVM running for 39.085)
2018-05-22 13:57:53.946  INFO 4952 --- [           main] e.u.a.e.incidashboard_e3b.DashboardTest  : Using base URL: 'http://localhost:61041'
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.226 sec <<< FAILURE! - in es.uniovi.asw.e3b.incidashboard_e3b.DashboardTest
testLogin(es.uniovi.asw.e3b.incidashboard_e3b.DashboardTest)  Time elapsed: 6.16 sec  <<< ERROR!
org.openqa.selenium.TimeoutException: Timed out after 2 seconds waiting for visibility of element located by By.xpath: //*[contains(@href,'login')]
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'XXXX', ip: '10.0.75.1', os.name: 'XXXXXX', os.arch: 'amd64', os.version: 'XX', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.htmlunit.HtmlUnitDriver
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementByXPath(HtmlUnitDriver.java:1155)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1707)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1703)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1357)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:1703)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:595)
        at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:899)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
        at es.uniovi.asw.e3b.incidashboard_e3b.utils.SeleniumUtils.EsperaCargaPaginaxpath(SeleniumUtils.java:66)
        at es.uniovi.asw.e3b.incidashboard_e3b.utils.SeleniumUtils.EsperaCargaPagina(SeleniumUtils.java:92)
        at es.uniovi.asw.e3b.incidashboard_e3b.po.PO_NavView.clickOption(PO_NavView.java:30)
        at es.uniovi.asw.e3b.incidashboard_e3b.DashboardTest.testLogin(DashboardTest.java:76)

Running es.uniovi.asw.e3b.incidashboard_e3b.ParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in es.uniovi.asw.e3b.incidashboard_e3b.ParserTest
2018-05-22 13:57:56.859  INFO 4952 --- [       Thread-8] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a353dff: startup date [Tue May 22 13:57:17 CEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@21457b14
2018-05-22 13:57:56.863  INFO 4952 --- [       Thread-8] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3ad875a6: startup date [Tue May 22 13:57:45 CEST 2018]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a353dff
2018-05-22 13:57:56.896  INFO 4952 --- [       Thread-8] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482647
2018-05-22 13:57:57.485  INFO 4952 --- [afka-consumer-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-05-22 13:57:57.485  INFO 4952 --- [       Thread-8] s.i.k.i.KafkaMessageDrivenChannelAdapter : stopped org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter@644c0e
2018-05-22 13:57:57.486  INFO 4952 --- [       Thread-8] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-05-22 13:57:57.488  INFO 4952 --- [       Thread-8] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-05-22 13:57:57.489  INFO 4952 --- [       Thread-8] o.s.i.channel.PublishSubscribeChannel    : Channel 'application:0.errorChannel' has 0 subscriber(s).
2018-05-22 13:57:57.489  INFO 4952 --- [       Thread-8] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
2018-05-22 13:57:57.496  INFO 4952 --- [afka-consumer-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-05-22 13:57:57.496  INFO 4952 --- [afka-consumer-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-05-22 13:57:57.578  INFO 4952 --- [afka-consumer-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-05-22 13:57:57.578  INFO 4952 --- [       Thread-8] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2018-05-22 13:57:57.662  INFO 4952 --- [       Thread-8] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-05-22 13:57:57.670  INFO 4952 --- [       Thread-8] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2018-05-22 13:57:57.679  INFO 4952 --- [       Thread-8] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000227: Running hbm2ddl schema export
2018-05-22 13:57:58.480  INFO 4952 --- [       Thread-8] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000230: Schema export complete
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Results :

Tests in error:
  DashboardTest.testLogin:76 » Timeout Timed out after 2 seconds waiting for vis...

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
~~~

**Comment by kilianpg** [comment]
Entorno de ejecución de la prueba unitaria:
~~~
mvn clean package docker:build docker:run -Dmaven.test.skip -Ddocker.filter=postgres,zookeeper,kafka,agents_e3b,incimanager_e3b 

mvn test
~~~

**Comment by dalvgui** [comment]
Me pondré con ello, revisaré las pruebas, ese error viene de las pruebas de selenium del testLogin que no encuentra un elemento concreto y salta la excepción del tiempo límite dedicado a buscar dicho elemento.

**Comment by dalvgui** [comment]
Estaría resuelta
