### ISSUE TITLE
Añadir botón Codecov

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/InciDashboard_e3b#6]
Añadir botón de Codacy en vuestro README.md

**Comment by ManuelJunco** [comment]
Añadido. Falta hacer que funcione correctamente

**Comment by UO244730** [comment]
Jacoco está descartado como lo que está dando problemas. Lo más seguro es que sean los tests.

**Comment by UO244730** [comment]
Los tests tampoco son. Creo que la única solución es eliminar las lambdas.

**Comment by miguelms95** [comment]
Si no se soluciona quitando esas lambdas de funcional, se puede pedir ayuda a @labra, para cerrar el issue. 
Es importante tener testeado y que se vea la cobertura de código testeado 👍

**Comment by ManuelJunco** [comment]
Quite código lambda pero el boton de Codecov sigue sin funcionar

**Comment by UO244730** [comment]
Me sale el siguiente error:

-------------------------------------------------------------------------------
Test set: inci_dashboard.test.DashboardTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 81.506 sec <<< FAILURE! - in inci_dashboard.test.DashboardTest
testLogin(inci_dashboard.test.DashboardTest)  Time elapsed: 5.675 sec  <<< ERROR!
org.openqa.selenium.TimeoutException: Timed out after 2 seconds waiting for visibility of element located by By.xpath: //*[contains(@hr$
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'sector7', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-38-generic', java.version: '1.8.$
Driver info: org.openqa.selenium.htmlunit.HtmlUnitDriver
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementByXPath(HtmlUnitDriver.java:1155)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1707)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1703)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1357)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:1703)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:595)
        at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:899)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
        at inci_dashboard.test.utils.SeleniumUtils.EsperaCargaPaginaxpath(SeleniumUtils.java:66)
        at inci_dashboard.test.utils.SeleniumUtils.EsperaCargaPagina(SeleniumUtils.java:92)
        at inci_dashboard.test.po.PO_NavView.clickOption(PO_NavView.java:30)
        at inci_dashboard.test.DashboardTest.testLogin(DashboardTest.java:71)

**Comment by UO244730** [comment]
Sobre el error de los tests, que se produce en el método clickOption de la clase PO_NavView.  Una de las posibilidades de la causa es que no le dé tiempo a cargar la página antes de que haga click (se solucionaría aumentando el timeout). Esto está descartado, he probado incluso con un timeout de 100 segundo y ni aún así. La otra causa puede ser que el path sea incorrecto, que a mí parecer está bien, pero no estoy seguro. 

Es posible que haya más errores aparte de ese, pero no podemos saber hasta que esté solucionado este primero.
